### PR TITLE
Update openlayers to set floor dimension value on WMTS REST layers

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Change openlayers submodule to camptocamp/openlayer and checkout branch cgxp-1.6 that add one commit.

### CODE REVIEW

**Comment by sbrunner** [comment]
Your sure that no one of the 24 pull request had a side effect ?

Personally I prefer to have a branch in the camptocamp clone with only the interesting pull request (or commit) ...

**Comment by arnaud-morvan** [comment]
Not sure to understand correctly.
That I understatd is that you ask me to create a branch in camptocamp/openlayers, checkout openlayers commit that is set in cpxp 1.6 branch, and add the only one commit I need to set WMTS dimensions parameter. Adn finnally change the remote in CGXP to camptocamp/openlayer.

**Comment by sbrunner** [comment]
Exactly :-)

**Comment by arnaud-morvan** [comment]
Done. Note that with this method, everyone will have to ```git submodule sync``` in cgxp folder.

**Comment by sbrunner** [comment]
Thanks, merge :-)

**Pull request merged**
