### PR TITLE
Fix noDataValue option in profile

### PR DESCRIPTION
**Pull request by rbovard**
To work with other noDataValue than `0`

See https://github.com/camptocamp/cgxp/pull/951#issuecomment-160554011 for history

### CODE REVIEW

**Comment by sbrunner** [comment]
Great, thanks @rbovard, I will merge when Travis will be happy :-)

**Comment by rbovard** [comment]
Thanks, it's a cowork with @kalbermattenm

**Comment by kalbermattenm** [comment]
This should also be ported to branch 1.6....

**Comment by sbrunner** [comment]
Done :-)

**Comment by kalbermattenm** [comment]
Thanks @sbrunner and @rbovard !

**Pull request merged**
