### PR TITLE
Cut polygons

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by sbrunner** [comment]
Difficult to review, do you have an URL to test ?

I see many commits for the "same" thing doesn't the following commits be merge?
 * Prepare layout for the cut wizard
 * Manage cut by drawing a new polygon
 * Manage cut by selecting features on map
 * Show buttons state (active/inactive) in cut wizard
 * Remove unecessary comment

**Comment by pgiraud** [comment]
The commits could indeed be squashed into a single one.

**Comment by sbrunner** [comment]
I think that's better :-)

**Comment by sbrunner** [comment]
Otherwise that looks good from me :-)

**Pull request merged**
