### PR TITLE
[Regression] The busy mask block the user relay too long

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by asaunier** [comment]
So now the loading message is removed when the PDF has been generated, not waiting the print status is updated. Is it really so long to perform the latter step?

**Comment by sbrunner** [comment]
less than 1s relay less than about 1min !

**Comment by sbrunner** [comment]
The question can be should we completely remove this mask with Mapfish print v3 ?

**Comment by asaunier** [comment]
> Less than 1s relay less than about 1min !

I fon't get it. The generation takes 1 sec and then you have to wait for 1 min?

**Comment by sbrunner** [comment]
The job generation take 1s, and the print takes 1 min, and the user is free to work between the and eventually create a new print in the queue :-)

**Comment by asaunier** [comment]
OK
On the other hand, if your remove the loading mask, the user will not know that his printing job is pending and will probably think it has failed => he will try to print again and again...

**Comment by sbrunner** [comment]
And he will see that his job will be queue and progress ...

**Comment by asaunier** [comment]
OK if there are information provided about the printing jobs in progress.

**Pull request merged**
