### PR TITLE
Zoom to the feature extent instead of recentering

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by sbrunner** [comment]
Is it a good idea for points?

**Comment by eleu** [comment]
For points, to be coherent, it should be the same behaviour as for a WFS Permalink.
f.e. https://geomapfish-demo.camptocamp.net/1.6/theme/Transport?wfs_layer=fuel&wfs_osm_id=303903676

**Comment by fredj** [comment]
Test with: https://geomapfish-demo.camptocamp.net/2.0/edit?debug&edit_layer=69&edit_id=33

If it's a point, the map in centered and zoomed to the maximum zoom level

**Comment by sbrunner** [comment]
> If it's a point, the map in centered and zoomed to the maximum zoom level

Yes and we usually don't want that ...

In the wfs permalink we configure a zoom for points: 
https://github.com/camptocamp/cgxp/blob/master/core/src/script/CGXP/plugins/WFSPermalink.js#L407

**Comment by fredj** [comment]
New version: the zoom level when reentering to a point is now configurable (default is 9)

**Comment by sbrunner** [comment]
Looks good, merge when Travis is happy :-)

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
