### PR TITLE
add possibility to set the default column width for grids 

### PR DESCRIPTION
**Pull request by ochriste**
ext default is 100px

### CODE REVIEW

**Comment by asaunier** [comment]
Is it OK if the default col width is now set to 100 px for projects that will upgrade to this version of CGXP?
If not perhaps the default value should be null?

**Comment by sbrunner** [comment]
Looks good, you just should do a rebase to fix Travis :-)

**Comment by sbrunner** [comment]
After #982 is merged :-)

**Comment by ochriste** [comment]
@asaunier 100 is the default value in Ext

**Comment by asaunier** [comment]
> @asaunier 100 is the default value in Ext

OK then!

**Pull request merged**
