### PR TITLE
Update OpenLayers 2

### PR DESCRIPTION
**Pull request by kalbermattenm**
To get https://github.com/camptocamp/openlayers/pull/3

Please review and eventually merge if happy

### CODE REVIEW

**Comment by sbrunner** [comment]
you should add 
```yaml
git:
    submodules: false
```
At the start of the `.travis.yaml` file to make the Travis tests pass :-)

**Comment by kalbermattenm** [comment]
Travis is still not happy... Did I do something wrong ?

**Comment by sbrunner** [comment]
I will have a look on that the next week :-)

**Comment by kalbermattenm** [comment]
No worries, I am on holidays anyway ;-)

**Comment by sbrunner** [comment]
Enjoy :-)

**Comment by sbrunner** [comment]
Should be rebased :-)

**Comment by kalbermattenm** [comment]
I just updated this branch and removed a commit which was replaced by https://github.com/camptocamp/cgxp/pull/1112

Is it OK like that ?

**Comment by sbrunner** [comment]
Can you do a rebase to remove the merge commit?

**Comment by kalbermattenm** [comment]
@sbrunner, I tried... but it looks like I made a big mess...

The strangest things about it, is that my local history looks good... :

image

**Comment by rbovard** [comment]
Haha, see https://github.com/camptocamp/ngeo/pull/2346#issuecomment-281357484

**Comment by kalbermattenm** [comment]
Thanks ;-)

**Comment by kalbermattenm** [comment]
This time, I think we are OK... Thanks a lot for the hint @rbovard 

@sbrunner, please merge if happy.

**Comment by sbrunner** [comment]
Many thanks @kalbermattenm

**Comment by kalbermattenm** [comment]
Thanks @sbrunner

**Pull request merged**
