### PR TITLE
Add EPSG2154 (aka lambert93) definition file

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by sbrunner** [comment]
What's this pull request ?
- non reviewed and merge !
- duplicate with #910 => merge issue !!

**Comment by arnaud-morvan** [comment]
I've made a pull request on 1.5 branch, asaunier said it was good, so I've merged on 1.5.
This is a cherry-pick on master. Maybe this is not the normal workflow.

**Comment by sbrunner** [comment]
and when I merger the branch 1.5 to the master (the correct way) I will have a conflict, especially for a new file ...

**Comment by arnaud-morvan** [comment]
Ok, this should only be pulled in 1.5 and you regulary merge 1.5 in master, sorry for the trouble.

**Pull request merged**
