### PR TITLE
add option neverUseCurrentContext

### PR DESCRIPTION
**Pull request by gilliM**

### CODE REVIEW

**Comment by sbrunner** [comment]
Thanks, merge :-)

**Comment by sbrunner** [comment]
And delete the branch :-)

**Comment by gilliM** [comment]
Or do i need to do a PR also ?

On Thu, Feb 19, 2015 at 12:32 PM, Stéphane Brunner <notifications@github.com
> wrote:

> And delete the branch :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camptocamp/cgxp/pull/915#issuecomment-75037067>.
>



-- 

*camp**to**camp*
INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

*Gillian Milani*

Ingénieur en environnement
Stagiaire

+41 21 619 10 10 (central)
+41 21 619 10 48 (direct)
*Camptocamp SA*
Quartier de l'Innovation EPFL, PSE-A
1015 Lausanne
Suisse

**Comment by sbrunner** [comment]
??? non just click on the button here ---> ------------------------------------------------------------------ vvv

**Comment by gilliM** [comment]
"Or do i need to do a PR also *in master*?"

**Comment by sbrunner** [comment]
no we will merge the 1.5 branch in master :-)

**Pull request merged**
