### PR TITLE
Show drawing layer again in query builder when expanding

### LINKED ISSUE #1037: QueryBuilder: spatial condition disappears when changing to themes
If you add a spatial condition to the **QueryBuilder**, the conditions geometry is displayed:
querybuilder_spatial_condition_displayed

If you change to the tab **themes** and go back to the **QueryBuilder**, the conditions geometry disappears although the query is stilll active.
querybuilder_spatial_condition_disappeared

(from https://github.com/camptocamp/baselstadt_mapbs/issues/53)

### PR DESCRIPTION
**Pull request by tsauerwein**
fixes #1037

### CODE REVIEW

**Comment by asaunier** [comment]
Make sense

**Comment by sbrunner** [comment]
Make sense But I work on exactly the same thing !!
see: #1045

**Comment by asaunier** [comment]
At least you have written exactly the same code :)

**Comment by sbrunner** [comment]
:-)

**Comment by tsauerwein** [comment]
Args, that was unfortunate! Feel free to close this PR (or your PR).

**Pull request merged**
