### PR TITLE
Cherry pick OpenLayers commit to fix mobile on Android

### PR DESCRIPTION
**Pull request by sbrunner**
to fix camptocamp/c2cgeoportal#944 on 1.5

### CODE REVIEW

**Comment by rbovard** [comment]
Oh thanks a lot @sbrunner!

**Comment by asaunier** [comment]
> to fix #944 on 1.5

Are you sure of the issue's id?

**Comment by asaunier** [comment]
Why don't you use the standard OL repo?

**Comment by rbovard** [comment]
> Are you sure of the issue's id?

It's https://github.com/camptocamp/c2cgeoportal/issues/944

**Comment by sbrunner** [comment]
@asaunier to get only the patch that fix our issue :-)

**Comment by sbrunner** [comment]
@asaunier issue ref updated

**Comment by asaunier** [comment]
> @asaunier to get only the patch that fix our issue :-)

Is it a problem to get all the other patches as well?
Sticking to the official OL repo would be easier for upgrading in the future, don't you think?

**Comment by sbrunner** [comment]
We don't want to take the risk to add an issue in a stabilization branch, the master branch will always be on the official repository :-)

**Comment by asaunier** [comment]
OK, please merge.

**Pull request merged**
