### PR TITLE
Remove notifications to mailing list

### PR DESCRIPTION
**Pull request by romanzoller**
I think the default notification settings (email to committer) should be sufficient, please merge if you agree.

### CODE REVIEW

**Comment by sbrunner** [comment]
Or just completely remove the .travis, it don't works anymore ...

**Comment by sbrunner** [comment]
Or just completely remove the .travis, it don't works anymore ...

**Comment by sbrunner** [comment]
Finally I directly disable it on Travis :-)

**Comment by romanzoller** [comment]
Just got some notification emails again => please merge this

**Pull request merged**
