### PR TITLE
Don't remove features when the FeaturesWindow is closed to be able to print them.

### LINKED ISSUE #904: Incompatibility between the printing tool and the FeaturesWindow
In GMF 1.5 (exact version ?), if the user opens the Printing panel after a query using the FeaturesWindow, the results window and the hilighted features are reset. Therefore not printed in the final PDF.

May be reproduced at http://mapfish-geoportal.demo-camptocamp.com/1.5/theme/%C3%89quipement?map_x=430139.70692019&map_y=5404457.9947359&map_zoom=14
* make a query => the FeaturesWindow opens and the results are hilighted on the map
* click on the printing button => the FeaturesWindow closes and the features are no longer hilighted
* query results are not available in the PDF

OK with http://mapfish-geoportal.demo-camptocamp.com/demo (GMF 1.4.x).

Might be related to https://github.com/camptocamp/cgxp/pull/762

### PR DESCRIPTION
**Pull request by sbrunner**
The worth case is closed when we open the print panel.

fix #904

### CODE REVIEW

**Comment by asaunier** [comment]
"on close" what?
Perhaps you mean "when closing the FeaturesWindow"?

Is there a way to remove the features after the FeaturesWindow has been closed?

**Comment by sbrunner** [comment]
Update commit comment

**Comment by asaunier** [comment]
What about
> Is there a way to remove the features after the FeaturesWindow has been closed?

It seems problematic to me because at the moment I see no other way to get rid of hilighted features. With this change, it will be impossible to remove them.

**Comment by sbrunner** [comment]
yes, clic where there no features, now it's wroth, it's impossible to print the query result :-(

**Comment by asaunier** [comment]
As you want. I don't find it very satisfaying to degrade the querying experience in order to improve the printing experience.
Isn't it possible to rather keep the FeaturesWindow opened while printing?

**Comment by sbrunner** [comment]
Why not but we will have too Windows one over the other ...

**Comment by sbrunner** [comment]
@ybolognini what do you think?

**Comment by sbrunner** [comment]
Modified to don't close the feature panel, ant remove the feature on close it :-)

**Comment by asaunier** [comment]
Not sure to understand what your change does. It prevents the featurewindow from closing when the GetFeature plugin is deactivated, right? So when the printing panel is open, the GetFeature plugin is deactivated but the window remains. Correct?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by asaunier** [comment]
At first sight, it looks OK.

**Pull request merged**
