### PR TITLE
Reset the orthoRef value after the error message

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by asaunier** [comment]
Should we really use a console.log to report the pb?

**Comment by sbrunner** [comment]
You purpose a window.alert ?

**Comment by asaunier** [comment]
Yes at least. console.log is no supported by IE.

**Comment by sbrunner** [comment]
done

**Comment by asaunier** [comment]
Ops, I missed the fact that there was a "if (console)" test.
Is it still necessary?

**Comment by sbrunner** [comment]
I also miss it than no :-) thanks :-)

**Comment by sbrunner** [comment]
done

**Comment by asaunier** [comment]
Please merge.

**Pull request merged**
