### PR TITLE
Remove unneeded comma in FTS

### PR DESCRIPTION
**Pull request by kalbermattenm**
Title says it all

PR goes into branch 1.6

Please review

### CODE REVIEW

**Comment by sbrunner** [comment]
Thanks, merge :-)

**Comment by kalbermattenm** [comment]
Sorry, I can't merge ;-)

**Comment by sbrunner** [comment]
:-), I didn't realise that's you make the pull request :-)

**Comment by kalbermattenm** [comment]
Hmmmm... Happy to feel part of the family :laughing:

**Pull request merged**
