### PR TITLE
Colors for search

### PR DESCRIPTION
**Pull request by gilliM**

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good :-)

**Comment by pgiraud** [comment]
Can we get a screenshot of what it looks like?

**Comment by gilliM** [comment]
colorpicker

**Comment by pgiraud** [comment]
Do the users understand what this means?
I'm curious to know how the request for this new feature was formulated.

On Wed, Mar 11, 2015 at 9:49 AM, gilliM <notifications@github.com> wrote:

> [image: colorpicker]
> <https://cloud.githubusercontent.com/assets/6716422/6592974/e584d6ce-c7d3-11e4-937a-637434602646.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camptocamp/cgxp/pull/921#issuecomment-78225014>.
>



-- 
Pierre GIRAUD
Géomaticien, Analyste

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 93
Mail : pierre.giraud@camptocamp.com
http://www.camptocamp.com

**Comment by asaunier** [comment]
Is it really useful to display the color code in the combo? Most users don't know what this means. Removing it would take less space and be less confusing.

And I agree that this tool is not intuitive. At least a tooltip would help figuring out the purpose of the color combo.

**Comment by gilliM** [comment]
You can also write color in english in the combobox, like "red" or "blue"

On Wed, Mar 11, 2015 at 10:31 AM, Alex Saunier <notifications@github.com>
wrote:

> Is it really useful to display the color code in the combo? Most users
> don't know what this means. Removing it would take less space and be less
> confusing.
>
> And I agree that this tool is not intuitive. At least a tooltip would help
> figuring out the purpose of the color combo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camptocamp/cgxp/pull/921#issuecomment-78230424>.
>



-- 

*camp**to**camp*
INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

*Gillian Milani*

Ingénieur en environnement
Stagiaire

+41 21 619 10 10 (central)
+41 21 619 10 48 (direct)
*Camptocamp SA*
Quartier de l'Innovation EPFL, PSE-A
1015 Lausanne
Suisse

**Comment by gilliM** [comment]
After a search on the ext plugin, i don't see how to remove the text from
the box. However, we can set the widht of the box small, even if the text
will be partially hidden. What do you think ?

**Comment by sbrunner** [comment]
Updated version without an arrow, and with a tooltip:
http://geomapfish.demo-camptocamp.com/sbrunner/

**Comment by asaunier** [comment]
Looks good. A german translation for the new tooltip in https://github.com/camptocamp/cgxp/commit/7e6facfc67bbb4dc2356d3d1cf8d7115099bbde6 would be nice!

**Comment by sbrunner** [comment]
@tsauerwein Do you have something to purpose ?
for https://github.com/camptocamp/cgxp/commit/c84d9d3a10a30c5d256bfc906ba7a35d57bd914e#diff-e500bb2d45b32bbc2b99ceeb4ab8ad0dR28

**Pull request merged**
