### PR TITLE
Allow undo and cutWizard to be disabled in Editing

### PR DESCRIPTION
**Pull request by pvalsecc**
Added two parameters that are true by default:
- enableCutWizard
- enableUndo

### CODE REVIEW

**Comment by tsauerwein** [comment]
Looks good to me!

**Comment by arnaud-morvan** [comment]
For the undo feature, this remove the undo button, but do not deactivate key shortcuts:

https://github.com/camptocamp/cgxp/blob/aa4346ff679af5383eca9f6d2dcf3159daced224/core/src/script/CGXP/plugins/Editing.js#L495

https://github.com/camptocamp/cgxp/blob/9280d767570b7bc05aadadad5abd0cd9f675eea1/geoext.ux/ux/FeatureEditing/lib/GeoExt.ux/FeatureEditorGrid.js#L328

**Comment by pvalsecc** [comment]
Good catch! The customer ticket was more about the buttons... @arnaud-morvan, do you think I should do another pull request for disabling the key presses as well?

**Comment by sbrunner** [comment]
I think that's better :-)

**Comment by arnaud-morvan** [comment]
I also think that it would be more consistent.

**Comment by pvalsecc** [comment]
OK, pull request there:
https://github.com/camptocamp/cgxp/pull/1047

**Pull request merged**
